allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
